# Generated by Django 5.0.6 on 2024-06-09 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('address_block', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('dob', models.DateTimeField()),
                ('doj', models.DateTimeField()),
                ('gender', models.CharField(max_length=2)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sites_app.department')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
